### ISSUE TITLE
test/modulo_usuario

### ISSUE THREAD

**Issue by CarlosR99** [jumahl/granosdeoro#9]
Debe de realizar las pruebas unitarias del modulo usuario.

Nota
Debe de crear la rama de dichas pruebas a partir de la rama test/develop la cual, la rama creada a partir de test debe de contar con las respectivas convenciones de git, al finalizar y comprobar el funcionamiento de dichas pruebas debe de realizar un pr teniendo en cuenta el modelo de trabajo de git flow (rama merge) hacia la rama test/develop

**Comment by jumahl** [comment]
![Image](https://github.com/user-attachments/assets/93aced84-c49f-4cd3-89fa-b842083e463f)

**Se ejecutaron las pruebas de usuario donde se verifico:**

- puede crear un usuario con rol y permisos valida confirmacion de password   
- valida longitud minima de password  
- Actualizar usuario sin cambiar password   
- Actualizar roles y permisos
